version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ['*']

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      nuget-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: docker
    directories:
      - /src/Services/*/InstaConnect.*.Presentation
    schedule:
      interval: weekly
    groups:
      docker:
        patterns: ['*']
