<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>all</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestCodeProject Condition="$(MSBuildProjectName.Contains('.Tests'))">true</IsTestCodeProject>
    <IsTestRunnerProject Condition="$(MSBuildProjectName.EndsWith('.Tests.Unit')) Or $(MSBuildProjectName.EndsWith('.Tests.Integration')) Or $(MSBuildProjectName.EndsWith('.Tests.Functional'))">true</IsTestRunnerProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(IsTestCodeProject)' != 'true'">
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests.Unit" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests.Integration" />
    <InternalsVisibleTo Include="$(MSBuildProjectName).Tests.Functional" />
  </ItemGroup>

  <PropertyGroup Condition="'$(IsTestCodeProject)' == 'true'">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestRunnerProject)' == 'true'">
    <Nullable>disable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestRunnerProject)' == 'true'">
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
