networks:
  instaconnect:

services:
  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel-lgtm
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./.containers/grafana:/data
    networks:
      - instaconnect

  mongodb:
    image: mongo:7
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./.containers/mongodb:/data/db
    networks:
      - instaconnect

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: >
      redis-server --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./.containers/redis/data:/data
    networks:
      - instaconnect

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./.containers/rabbitmq/data:/var/lib/rabbitmq
      - ./.containers/rabbitmq/log:/var/log/rabbitmq
    networks:
      - instaconnect

  identity-svc:
    image: ${DOCKER_REGISTRY-}identity-svc
    container_name: identity-svc
    build:
      context: .
      dockerfile: src/Services/Identity/InstaConnect.Identity.Presentation/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      AccessTokenConfiguration__SecurityKey: "${ACCESS_TOKEN_SECURITY_KEY}"
      MongoConfiguration__ConnectionString: "Server=mongodb;Database=instaconnect.identity;User Id=${MONGO_USERNAME};Password=${MONGO_PASSWORD};TrustServerCertificate=True;"
      RabbitMqConfiguration__ConnectionString: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672/"
      RedisConfiguration__ConnectionString: "redis:6379,password=${REDIS_PASSWORD},abortConnect=False"
      CloudinaryConfiguration__CloudName: ${CLOUDINARY_CLOUD_NAME}
      CloudinaryConfiguration__ApiKey: ${CLOUDINARY_API_KEY}
      CloudinaryConfiguration__ApiSecret: ${CLOUDINARY_API_SECRET}
    ports:
      - "8083:80"
    depends_on:
      - otel-lgtm
      - mongodb
      - rabbitmq
      - redis
    networks:
      - instaconnect

  posts-svc:
    image: ${DOCKER_REGISTRY-}posts-svc
    container_name: posts-svc
    build:
      context: .
      dockerfile: src/Services/Posts/InstaConnect.Posts.Presentation/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      AccessTokenConfiguration__SecurityKey: "${ACCESS_TOKEN_SECURITY_KEY}"
      MongoConfiguration__ConnectionString: "Server=mongodb;Database=instaconnect.posts;User Id=${MONGO_USERNAME};Password=${MONGO_PASSWORD};TrustServerCertificate=True;"
      RabbitMqConfiguration__ConnectionString: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672/"
      RedisConfiguration__ConnectionString: "redis:6379,password=${REDIS_PASSWORD},abortConnect=False"
    ports:
      - "8082:80"
    depends_on:
      - otel-lgtm
      - mongodb
      - rabbitmq
    networks:
      - instaconnect

  chats-svc:
    image: ${DOCKER_REGISTRY-}chats-svc
    container_name: chats-svc
    build:
      context: .
      dockerfile: src/Services/Chats/InstaConnect.Chats.Presentation/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      AccessTokenConfiguration__SecurityKey: "${ACCESS_TOKEN_SECURITY_KEY}"
      MongoConfiguration__ConnectionString: "Server=mongodb;Database=instaconnect.chats;User Id=${MONGO_USERNAME};Password=${MONGO_PASSWORD};TrustServerCertificate=True;"
      RabbitMqConfiguration__ConnectionString: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672/"
      RedisConfiguration__ConnectionString: "redis:6379,password=${REDIS_PASSWORD},abortConnect=False"
    ports:
      - "8081:80"
    depends_on:
      - otel-lgtm
      - mongodb
      - rabbitmq
    networks:
      - instaconnect

  follows-svc:
    image: ${DOCKER_REGISTRY-}follows-svc
    container_name: follows-svc
    build:
      context: .
      dockerfile: src/Services/Follows/InstaConnect.Follows.Presentation/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      AccessTokenConfiguration__SecurityKey: "${ACCESS_TOKEN_SECURITY_KEY}"
      MongoConfiguration__ConnectionString: "Server=mongodb;Database=instaconnect.follows;User Id=${MONGO_USERNAME};Password=${MONGO_PASSWORD};TrustServerCertificate=True;"
      RabbitMqConfiguration__ConnectionString: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672/"
      RedisConfiguration__ConnectionString: "redis:6379,password=${REDIS_PASSWORD},abortConnect=False"
    ports:
      - "8080:80"
    depends_on:
      - otel-lgtm
      - mongodb
      - rabbitmq
    networks:
      - instaconnect

  nginx:
    image: nginx:latest
    container_name: gateway-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - identity-svc
      - posts-svc
      - chats-svc
      - follows-svc
    networks:
      - instaconnect
