networks:
  instaconnect:

services:
  sqlserver:
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
            SA_PASSWORD: "password123!"
            ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/mysql:/var/opt/mssql/data
    networks:
      - instaconnect

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672" 
    volumes:
      - ./.containers/rabbit-mq/data/:/var/lib/rabbitmq
      - ./.containers/rabbit-mq/log/:/var/log/rabbitmq
    networks:
      - instaconnect

  gateway-svc:
    image: ${DOCKER_REGISTRY-}gateway-svc
    build:
      context: .
      dockerfile: src/Gateway/InstaConnect.Gateway.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ReverseProxy__Clusters__users-cluster__Destinations__destination1__Address: http://user-svc
      ReverseProxy__Clusters__posts-cluster__Destinations__destination1__Address: http://post-svc
      ReverseProxy__Clusters__messages-cluster__Destinations__destination1__Address: http://message-svc
      ReverseProxy__Clusters__follows-cluster__Destinations__destination1__Address: http://follow-svc
    ports:
      - "5100:80"
    networks:
      - instaconnect
  
  users-svc:
    image: ${DOCKER_REGISTRY-}users-svc
    build: 
      context: .
      dockerfile: src/Services/Users/InstaConnect.Users.Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=instaconnect.users;User Id=sa;Password=password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
      MessageBrokerOptions__Host: amqp://rabbitmq:5672
      MessageBrokerOptions__Username: guest
      MessageBrokerOptions__Password: guest
      AdminOptions__Email: admin@instaconnect.com
      AdminOptions__Password: SecureAdminPass123!
      TokenOptions__AccessTokenSecurityKey: 6R9f6d1Y4Z$0^8Y&S2e3nF4*G6u7D0#L
      TokenOptions__AccountTokenSecurityKey: 8T1z2Q5w&3E8^9N@R7y6K0L3*F6D1#P4
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5200:80"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - instaconnect

  posts-svc:
    image: ${DOCKER_REGISTRY-}posts-svc
    build:
      context: .
      dockerfile: src/Services/Posts/InstaConnect.Posts.Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=instaconnect.posts;User Id=sa;Password=password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
      MessageBrokerOptions__Host: amqp://rabbitmq:5672
      MessageBrokerOptions__Username: guest
      MessageBrokerOptions__Password: guest
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5300:80"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - instaconnect

  messages-svc:
    image: ${DOCKER_REGISTRY-}messages-svc
    build:
      context: .
      dockerfile: src/Services/Messages/InstaConnect.Messages.Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=instaconnect.messages;User Id=sa;Password=password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
      MessageBrokerOptions__Host: amqp://rabbitmq:5672
      MessageBrokerOptions__Username: guest
      MessageBrokerOptions__Password: guest
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5400:80"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - instaconnect

  follows-svc:
    image: ${DOCKER_REGISTRY-}follows-svc
    build:
      context: .
      dockerfile: src/Services/Follows/InstaConnect.Follows.Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=instaconnect.follows;User Id=sa;Password=password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
      MessageBrokerOptions__Host: amqp://rabbitmq:5672
      MessageBrokerOptions__Username: guest
      MessageBrokerOptions__Password: guest
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5500:80"
    depends_on:
      - sqlserver
      - rabbitmq
    networks:
      - instaconnect
