version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
    networks:
      backend:

  rabbitmq:
     image: rabbitmq:management
     environment: 
         RABBITMQ_DEFAULT_HOST: amqp://instaconnect.rabbitmq:5672
         RABBITMQ_DEFAULT_USER: mihail
         RABBITMQ_DEFAULT_PASS: mihail
     volumes:
       - ./.containers/rabbit-mq/data/:/var/lib/rabbitmq
       - ./.containers/rabbit-mq/log/:/var/log/rabbitmq
     networks:
       - backend

  instaconnect.gateway.web:
    image: vtumihail/instaconnectusersweb:latest
    build:
      context: .
      dockerfile: InstaConnect.Gateway.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:5100"
      - "5101:5101"
    networks:
      - backend

  instaconnect.users.web:
    image: vtumihail/instaconnect.users.web:latest
    build: 
      context: .
      dockerfile: InstaConnect.Users.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=instaconnect.users
      - MessageBrokerOptions__Host=amqp://instaconnect.rabbitmq:5672
      - MessageBrokerOptions__Username=mihail
      - MessageBrokerOptions__Password=mihail
      - AdminOptions__Email=admin@instaconnect.com
      - AdminOptions__Password=SecureAdminPass123!
      - TokenSecurityOptions__AccessTokenSecurityKey=cuk
      - TokenSecurityOptions__EmailConfirmationTokenSecurityKey=cuk
      - TokenSecurityOptions__PasswordResetTokenSecurityKey=cuk
    ports:
      - "5200:5200"
      - "5201:5201"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - backend

  instaconnect.posts.web:
    image: vtumihail/instaconnectpostsweb:latest
    build:
      context: .
      dockerfile: InstaConnect.Posts.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=instaconnect.users
      - MessageBrokerOptions__Host=amqp://instaconnect.rabbitmq:5672
      - MessageBrokerOptions__Username=mihail
      - MessageBrokerOptions__Password=mihail
    ports:
      - "5300:5300"
      - "5301:5301"
    networks:
      - backend

  instaconnect.messages.web:
    image: vtumihail/instaconnectmessagesweb:latest
    build:
      context: .
      dockerfile: InstaConnect.Messages.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=instaconnect.users
      - MessageBrokerOptions__Host=amqp://instaconnect.rabbitmq:5672
      - MessageBrokerOptions__Username=mihail
      - MessageBrokerOptions__Password=mihail
    ports:
      - "5400:5400"
      - "5401:5401"
    networks:
      - backend

  instaconnect.follows.web:
    image: vtumihail/instaconnectfollowsweb:latest
    build:
      context: .
      dockerfile: InstaConnect.Follows.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=instaconnect.users
      - MessageBrokerOptions__Host=amqp://instaconnect.rabbitmq:5672
      - MessageBrokerOptions__Username=mihail
      - MessageBrokerOptions__Password=mihail
    ports:
      - "5500:5500"
      - "5501:5501"
    networks:
      - backend

networks:
  backend:
    ipam:
      config:
        - subnet: 10.5.0.0/16