using InstaConnect.Common.Infrastructure.Features.Databases.Abstractions;

namespace InstaConnect.Posts.Infrastructure.Features.PostCommentLikes.Abstractions;

public interface IPostCommentLikeResponseFluent : IMongoDbResponseFluent<PostCommentLikeResponse>
{
	public IPostCommentLikeResponseFluent ApplySorting(PostCommentLikesSortingQuery query);
	public IPostCommentLikeResponseFluent ApplySorting(PostCommentLikesForUserSortingQuery query);
	public IPostCommentLikeResponseFluent ApplyPagination(PostCommentLikesPaginationQuery query);
}
