namespace InstaConnect.Identity.Infrastructure.Features.ForgotPasswordTokens.Abstractions;

public interface IForgotPasswordTokenIncludePropertyFactory
    : IIncluderFactory<ForgotPasswordTokenIncludeProperty, IForgotPasswordTokenIncludeProperty, ForgotPasswordToken>;
