namespace InstaConnect.Identity.Events.Features.EmailConfirmationTokens;

public record EmailConfirmationTokenDeletedEventRequest(EmailConfirmationTokenEventRequest EmailConfirmationToken) : IEventRequest;
