namespace InstaConnect.Identity.Infrastructure.Features.EmailConfirmationTokens.Abstractions;

public interface IEmailConfirmationTokenIncludePropertyFactory
    : IIncluderFactory<EmailConfirmationTokenIncludeProperty, IEmailConfirmationTokenIncludeProperty, EmailConfirmationToken>;
