namespace InstaConnect.Posts.Application.Features.PostCommentLikes.Queries.GetAll;

public record GetAllPostCommentLikesQueryResponse(PostCommentLikeCollectionQueryResponse PostCommentLikeCollection);
