events {}

http {
    upstream identity { 
        server identity-svc:80; 
    }
    upstream posts { 
        server posts-svc:80; 
    }
    upstream chats { 
        server chats-svc:80; 
    }
    upstream follows { 
        server follows-svc:80; 
    }

    server {
        listen 80;
        server_name $hostname;

        location /identity/ {
            proxy_pass http://identity/;
        }

        location /posts/ {
            proxy_pass http://posts/;
        }

        location /chats/ {
            proxy_pass http://chats/;
        }

        location /follows/ {
            proxy_pass http://follows/;
        }

        location /nginx_status {
            stub_status;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }
}