<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  	<IsTestProject>false</IsTestProject>
  </PropertyGroup>
  
  <ItemGroup>
  	<PackageReference Include="MediatR" />
  </ItemGroup>
  
  <ItemGroup>
  	<ProjectReference Include="..\..\..\Common\InstaConnect.Common.Infrastructure.Tests\InstaConnect.Common.Infrastructure.Tests.csproj" />
  	<ProjectReference Include="..\InstaConnect.Identity.Tests\InstaConnect.Identity.Tests.csproj" />
  </ItemGroup>

</Project>
