events {}

http {
    upstream identity { server identity-svc:80; }
    upstream posts { server posts-svc:80; }
    upstream chats { server chats-svc:80; }
    upstream follows { server follows-svc:80; }

    server {
        listen 80;

        location /identity/ {
            proxy_pass http://identity/api/v1/identity/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /posts/ {
            proxy_pass http://posts/api/v1/posts/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /chats/ {
            proxy_pass http://chats/api/v1/chats/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /follows/ {
            proxy_pass http://follows/api/v1/follows/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}