using InstaConnect.Identity.Application.Features.EmailConfirmationTokens.Models;

namespace InstaConnect.Identity.Application.Features.EmailConfirmationTokens.Commands.Verify;

public record VerifyEmailConfirmationTokenCommandRequest(EmailConfirmationTokenIdPayload Id) : ICommandRequest;
