namespace InstaConnect.Follows.Infrastructure.Features.Follows.Abstractions;

internal interface IFollowsForFollowingSortTermerFactory : ISortTermerFactory<FollowsForFollowingSortTerm, IFollowsForFollowingSortTermer, FollowResponse>;
