namespace InstaConnect.Follows.Infrastructure.Features.Follows.Abstractions;

internal interface IFollowsForFollowerSortTermerFactory : ISortTermerFactory<FollowsForFollowerSortTerm, IFollowsForFollowerSortTermer, FollowResponse>;
