<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InstaConnect.Posts.Domain.Tests\InstaConnect.Posts.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup Label="Common">
    <Using Include="InstaConnect.Common.Tests.Features.Abstractions" />
    <Using Include="InstaConnect.Common.Tests.Features.Helpers" />
    <Using Include="InstaConnect.Common.Tests.Features.Assertions" />
    <Using Include="InstaConnect.Common.Tests.Features.Utilities" />
    <Using Include="InstaConnect.Posts.Tests.Features.Common.Utilities" />
  </ItemGroup>

</Project>
