namespace InstaConnect.Posts.Presentation.Features.PostCommentLikes.Models.Responses;

public record GetAllPostCommentLikesForUserApiResponse(PostCommentLikeCollectionApiResponse PostCommentLikeCollection);
